const MEMBER_PREFIX = 'spv.member';
const TXPROPOSAL_PREFIX = 'spv.txproposal';
const MEMPROPOSAL_PREFIX = 'spv.memproposal';
const VOTE_PREFIX = 'spv.vote';
const SPV_PREFIX = 'spv.spv';


const EARTH_ACCOUNT_TYPE_ADMIN = 'admin';
const USER_ROLES = ['admin', 'user', 'spv'];


const SPV_MODEL_MEMBER = 'SPV.Member';
const SPV_MODEL_PROPOSAL = 'SPV.Proposal';
const SPV_MODEL = 'SPV';

const SPV_CHAINCODE_NAME = 'SPV';
const SPV_CHAINCODE_ID = '30a24079-9922-4382-8763-018a3da96d4a';
const EARTH_CHAINCODE_ID = 'e6d1b325-5e43-4a05-a79f-75eecf864334';

module.exports = {
	SPV_PREFIX,
	MEMBER_PREFIX,
	TXPROPOSAL_PREFIX,
	MEMPROPOSAL_PREFIX,
	VOTE_PREFIX,

	EARTH_ACCOUNT_TYPE_ADMIN,
	USER_ROLES,

	SPV_MODEL_MEMBER,
	SPV_MODEL_PROPOSAL,
	SPV_MODEL,

	SPV_CHAINCODE_NAME,
	SPV_CHAINCODE_ID,
	EARTH_CHAINCODE_ID,

};
